name: ramadan_cmpetitions
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  image_picker: ^0.8.4+10
  carousel_slider: ^4.0.0
  flutter_slidable: ^1.2.0
  url_launcher: ^6.0.20
  charts_flutter: ^0.12.0
  # connectivity_plus: ^2.2.1
  syncfusion_flutter_charts: ^19.4.53
  smooth_page_indicator: ^1.0.0+2
  dio: ^4.0.4
  shared_preferences: ^2.0.13
  flutter_secure_storage: ^5.0.2
  jwt_decoder: ^2.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/wird_app_icon.png"

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  fonts:
    - family: Ptbldhad
      fonts:
        - asset: assets/fonts/Ptbldhad.ttf
          style: italic
          weight: 300
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Black.ttf
        - asset: assets/fonts/Tajawal-Bold.ttf
        - asset: assets/fonts/Tajawal-Light.ttf
        - asset: assets/fonts/Tajawal-Regular.ttf
        - asset: assets/fonts/Tajawal-Medium.ttf
